# Reusable workflow for PRs; to eject, you can replace this file with
# https://github.com/ryansonshine/ryansonshine/blob/main/.github/workflows/pr.yml
name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Run Test Suite
        run: npm run test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
